{
 "title": "Dashboard consumi",
 "time": { "from": "2025-06-12T11:42:22.000Z", "to": "2025-06-14T11:42:22.000Z" },
 "panels": [
  { "title": "Potenza attuale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_rilevamento\r\nFROM rilevamento ORDER BY timestamp_rilevamento DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Watt consumati di media per 48h",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    date_trunc('hour', timestamp_rilevamento) +\r\n    (extract(minute from timestamp_rilevamento)::int / 15) * interval '15 minutes' AS intervallo_15min,\r\n    MAX(watt_rilevati) AS max_watt,\r\n    MIN(watt_rilevati) AS min_watt,\r\n    AVG(watt_rilevati) AS media_watt\r\nFROM\r\n    Rilevamento\r\nGROUP BY\r\n    intervallo_15min\r\nORDER BY\r\n    intervallo_15min\r\n"
    }
   ]
  },
  {
   "title": "Potenza attuale",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ROUND(watt_rilevati::NUMERIC / 1000, 3) AS potenza_ultima_kw\r\nFROM\r\n  rilevamento\r\nORDER BY\r\n  timestamp_rilevamento DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  r1.timestamp_rilevamento,\r\n  r1.watt_rilevati AS \"Ufficio 1\",\r\n  r2.watt_rilevati AS \"Magazzino\",\r\n  r3.watt_rilevati AS \"Laboratorio\"\r\nFROM\r\n  Rilevamento r1\r\nJOIN\r\n  Sensore s1 ON r1.codice_sensore = s1.id_sensore AND s1.nome_sensore = 'Sensore Elettricità Ufficio 1'\r\nJOIN\r\n  Rilevamento r2 ON r1.timestamp_rilevamento = r2.timestamp_rilevamento\r\nJOIN\r\n  Sensore s2 ON r2.codice_sensore = s2.id_sensore AND s2.nome_sensore = 'Sensore Elettricità Magazzino'\r\nJOIN\r\n  Rilevamento r3 ON r1.timestamp_rilevamento = r3.timestamp_rilevamento\r\nJOIN\r\n  Sensore s3 ON r3.codice_sensore = s3.id_sensore AND s3.nome_sensore = 'Sensore Elettricità Laboratorio'\r\nWHERE\r\n  r1.timestamp_rilevamento >= now() - interval '2 days'\r\nORDER BY\r\n  r1.timestamp_rilevamento;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  r1.timestamp_rilevamento,\r\n  r1.ampere_rilevati AS \"Ufficio 1\",\r\n  r2.ampere_rilevati AS \"Magazzino\",\r\n  r3.ampere_rilevati AS \"Laboratorio\"\r\nFROM\r\n  Rilevamento r1\r\nJOIN\r\n  Sensore s1 ON r1.codice_sensore = s1.id_sensore AND s1.nome_sensore = 'Sensore Elettricità Ufficio 1'\r\nJOIN\r\n  Rilevamento r2 ON r1.timestamp_rilevamento = r2.timestamp_rilevamento\r\nJOIN\r\n  Sensore s2 ON r2.codice_sensore = s2.id_sensore AND s2.nome_sensore = 'Sensore Elettricità Magazzino'\r\nJOIN\r\n  Rilevamento r3 ON r1.timestamp_rilevamento = r3.timestamp_rilevamento\r\nJOIN\r\n  Sensore s3 ON r3.codice_sensore = s3.id_sensore AND s3.nome_sensore = 'Sensore Elettricità Laboratorio'\r\nWHERE\r\n  r1.timestamp_rilevamento >= now() - interval '2 days'\r\nORDER BY\r\n  r1.timestamp_rilevamento;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  r1.timestamp_rilevamento,\r\n  r1.volt_rilevati AS \"Ufficio 1\",\r\n  r2.volt_rilevati AS \"Magazzino\",\r\n  r3.volt_rilevati AS \"Laboratorio\"\r\nFROM\r\n  Rilevamento r1\r\nJOIN\r\n  Sensore s1 ON r1.codice_sensore = s1.id_sensore AND s1.nome_sensore = 'Sensore Elettricità Ufficio 1'\r\nJOIN\r\n  Rilevamento r2 ON r1.timestamp_rilevamento = r2.timestamp_rilevamento\r\nJOIN\r\n  Sensore s2 ON r2.codice_sensore = s2.id_sensore AND s2.nome_sensore = 'Sensore Elettricità Magazzino'\r\nJOIN\r\n  Rilevamento r3 ON r1.timestamp_rilevamento = r3.timestamp_rilevamento\r\nJOIN\r\n  Sensore s3 ON r3.codice_sensore = s3.id_sensore AND s3.nome_sensore = 'Sensore Elettricità Laboratorio'\r\nWHERE\r\n  r1.timestamp_rilevamento >= now() - interval '2 days'\r\nORDER BY\r\n  r1.timestamp_rilevamento;\r\n"
    }
   ]
  },
  {
   "title": "Consumi oggi, questo mese, quest'anno",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Oggi",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH ultimo AS (\r\n  SELECT MAX(timestamp_rilevamento) AS ts_max FROM Rilevamento\r\n),\r\ndati AS (\r\n  SELECT\r\n    timestamp_rilevamento,\r\n    watt_rilevati,\r\n    LEAD(timestamp_rilevamento) OVER (ORDER BY timestamp_rilevamento) AS ts_next,\r\n    LEAD(watt_rilevati) OVER (ORDER BY timestamp_rilevamento) AS watt_next,\r\n    (SELECT ts_max FROM ultimo) AS ts_max\r\n  FROM Rilevamento\r\n  WHERE timestamp_rilevamento >= (SELECT ts_max FROM ultimo) - INTERVAL '2 days'\r\n)\r\nSELECT\r\n  ROUND(\r\n    SUM(\r\n      (EXTRACT(EPOCH FROM (ts_next - timestamp_rilevamento)) / 3600)\r\n      * ((watt_rilevati + watt_next) / 2) / 1000\r\n    )::NUMERIC, 3) AS kWh_oggi\r\nFROM dati\r\nWHERE ts_next IS NOT NULL\r\n  AND timestamp_rilevamento >= date_trunc('day', (SELECT ts_max FROM ultimo));\r\n"
    }
   ]
  },
  {
   "title": "Grafico di oggi",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH ultimo AS (\r\n  SELECT MAX(timestamp_rilevamento) AS ts_max FROM Rilevamento\r\n),\r\ndati AS (\r\n  SELECT\r\n    timestamp_rilevamento,\r\n    watt_rilevati,\r\n    LEAD(timestamp_rilevamento) OVER (ORDER BY timestamp_rilevamento) AS ts_next,\r\n    LEAD(watt_rilevati) OVER (ORDER BY timestamp_rilevamento) AS watt_next\r\n  FROM Rilevamento\r\n  WHERE timestamp_rilevamento >= date_trunc('day', (SELECT ts_max FROM ultimo))\r\n    AND timestamp_rilevamento < date_trunc('day', (SELECT ts_max FROM ultimo)) + INTERVAL '1 day'\r\n),\r\nconsumo_orario AS (\r\n  SELECT\r\n    TO_CHAR(timestamp_rilevamento, 'HH24') AS ora,\r\n    (EXTRACT(EPOCH FROM (ts_next - timestamp_rilevamento)) / 3600)\r\n    * ((watt_rilevati + watt_next) / 2) / 1000 AS kWh\r\n  FROM dati\r\n  WHERE ts_next IS NOT NULL\r\n)\r\nSELECT\r\n  ora,\r\n  ROUND(SUM(kWh)::numeric, 3) AS kWh_per_ora\r\nFROM consumo_orario\r\nGROUP BY ora\r\nORDER BY ora::int;\r\n"
    }
   ]
  },
  {
   "title": "Questo mese",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH ultimo AS (\r\n  SELECT MAX(timestamp_rilevamento) AS ts_max FROM Rilevamento\r\n),\r\ndati AS (\r\n  SELECT\r\n    timestamp_rilevamento,\r\n    watt_rilevati,\r\n    LEAD(timestamp_rilevamento) OVER (ORDER BY timestamp_rilevamento) AS ts_next,\r\n    LEAD(watt_rilevati) OVER (ORDER BY timestamp_rilevamento) AS watt_next\r\n  FROM Rilevamento\r\n  WHERE timestamp_rilevamento >= date_trunc('month', (SELECT ts_max FROM ultimo))\r\n)\r\nSELECT\r\n  ROUND(\r\n    SUM(\r\n      (EXTRACT(EPOCH FROM (ts_next - timestamp_rilevamento)) / 3600)\r\n      * ((watt_rilevati + watt_next) / 2) / 1000\r\n    )::NUMERIC, 3\r\n  ) AS kWh_mese\r\nFROM dati\r\nWHERE ts_next IS NOT NULL;\r\n"
    }
   ]
  },
  {
   "title": "Grafico di questo mese",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "WITH ultimo AS (\r\n  SELECT MAX(timestamp_rilevamento) AS ts_max FROM Rilevamento\r\n),\r\ndati AS (\r\n  SELECT\r\n    timestamp_rilevamento,\r\n    watt_rilevati,\r\n    LEAD(timestamp_rilevamento) OVER (\r\n      PARTITION BY DATE(timestamp_rilevamento)\r\n      ORDER BY timestamp_rilevamento\r\n    ) AS ts_next,\r\n    LEAD(watt_rilevati) OVER (\r\n      PARTITION BY DATE(timestamp_rilevamento)\r\n      ORDER BY timestamp_rilevamento\r\n    ) AS watt_next,\r\n    (SELECT date_trunc('month', ts_max) FROM ultimo) AS inizio_mese\r\n  FROM Rilevamento\r\n  WHERE timestamp_rilevamento >= (SELECT date_trunc('month', ts_max) FROM ultimo)\r\n)\r\nSELECT\r\n  DATE(timestamp_rilevamento) AS giorno,\r\n  ROUND(SUM(\r\n    (EXTRACT(EPOCH FROM (ts_next - timestamp_rilevamento)) / 3600)\r\n    * ((watt_rilevati + watt_next) / 2) / 1000\r\n  )::NUMERIC, 3) AS kWh_giornalieri\r\nFROM dati\r\nWHERE ts_next IS NOT NULL\r\nGROUP BY giorno\r\nORDER BY giorno;\r\n"
    }
   ]
  },
  {
   "title": "Anno",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Grafico annuale",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {}
   ]
  },
  { "title": "Massimi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  MAX(ABS(ampere_rilevati)) AS \"Ufficio 1 A max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 1\r\n  AND timestamp_rilevamento BETWEEN \r\n    ($__timeFrom()::timestamp - INTERVAL '15 minutes') AND \r\n    ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  ABS(AVG(ampere_rilevati)) AS \"I1 avg\",\r\n  ABS(MAX(ampere_rilevati)) AS \"I1 max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 1\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento ASC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(ABS(volt_rilevati)) AS \"Ufficio 1 Vmax\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 1\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  ABS(AVG(CASE WHEN codice_sensore = 1 THEN volt_rilevati END)) AS \"V1 avg\",\r\n  ABS(MAX(CASE WHEN codice_sensore = 1 THEN volt_rilevati END)) AS \"V1 max\"\r\nFROM Rilevamento\r\nWHERE timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  AND codice_sensore = 1\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento ASC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  MAX(ABS(ampere_rilevati)) AS \"Magazzino A max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 2\r\n  AND timestamp_rilevamento BETWEEN\r\n    ($__timeFrom()::timestamp - INTERVAL '15 minutes') AND\r\n    ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  ABS(AVG(ampere_rilevati)) AS \"I2 avg\",\r\n  ABS(MAX(ampere_rilevati)) AS \"I2 max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 2\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento ASC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(ABS(volt_rilevati)) AS \"Magazzino Vmax\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 2\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  ABS(AVG(CASE WHEN codice_sensore = 2 THEN volt_rilevati END)) AS \"V2 avg\",\r\n  ABS(MAX(CASE WHEN codice_sensore = 2 THEN volt_rilevati END)) AS \"V2 max\"\r\nFROM Rilevamento\r\nWHERE timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  AND codice_sensore = 2\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento ASC;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  MAX(ABS(ampere_rilevati)) AS \"Laboratorio Amax\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 3\r\n  AND timestamp_rilevamento BETWEEN \r\n    ($__timeFrom()::timestamp - INTERVAL '15 minutes') AND \r\n    ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  ABS(AVG(ampere_rilevati)) AS \"I3 avg\",\r\n  ABS(MAX(ampere_rilevati)) AS \"I3 max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 3\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento ASC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  MAX(ABS(volt_rilevati)) AS \"Laboratorio Vmax\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 3\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  ABS(AVG(CASE WHEN codice_sensore = 3 THEN volt_rilevati END)) AS \"V3 avg\",\r\n  ABS(MAX(CASE WHEN codice_sensore = 3 THEN volt_rilevati END)) AS \"V3 max\"\r\nFROM Rilevamento\r\nWHERE timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                               AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  AND codice_sensore = 3\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento ASC;"
    }
   ]
  },
  { "title": "Fase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Carico medio per fase",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH intervallo AS (\r\n  SELECT\r\n    timestamp_rilevamento,\r\n    codice_sensore,\r\n    watt_rilevati,\r\n    LEAD(timestamp_rilevamento) OVER (PARTITION BY codice_sensore ORDER BY timestamp_rilevamento) AS ts_next\r\n  FROM Rilevamento\r\n  WHERE timestamp_rilevamento > ($__timeFrom()::timestamp - INTERVAL '1 hour')\r\n    AND timestamp_rilevamento < ($__timeTo()::timestamp + INTERVAL '1 hour')\r\n    AND codice_sensore IN (1, 2, 3)\r\n),\r\nenergia_per_fase AS (\r\n  SELECT\r\n    codice_sensore,\r\n    SUM(\r\n      EXTRACT(EPOCH FROM (ts_next - timestamp_rilevamento))/3600 * watt_rilevati / 1000\r\n    ) AS energia_kwh\r\n  FROM intervallo\r\n  WHERE ts_next IS NOT NULL\r\n  GROUP BY codice_sensore\r\n),\r\ntotale AS (\r\n  SELECT SUM(energia_kwh) AS energia_totale FROM energia_per_fase\r\n)\r\nSELECT\r\n  100 * COALESCE((SELECT energia_kwh FROM energia_per_fase WHERE codice_sensore = 1), 0) / NULLIF((SELECT energia_totale FROM totale),0) AS \"Ufficio 1\",\r\n  100 * COALESCE((SELECT energia_kwh FROM energia_per_fase WHERE codice_sensore = 2), 0) / NULLIF((SELECT energia_totale FROM totale),0) AS \"Magazzino\",\r\n  100 * COALESCE((SELECT energia_kwh FROM energia_per_fase WHERE codice_sensore = 3), 0) / NULLIF((SELECT energia_totale FROM totale),0) AS \"Laboratorio\";\r\n"
    }
   ]
  },
  {
   "title": "Carichi Fasi Media 15 min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp_rilevamento AS ts,\r\n  MAX(CASE WHEN codice_sensore = 1 THEN watt_rilevati ELSE NULL END) AS \"Ufficio 1\",\r\n  MAX(CASE WHEN codice_sensore = 2 THEN watt_rilevati ELSE NULL END) AS \"Magazzino\",\r\n  MAX(CASE WHEN codice_sensore = 3 THEN watt_rilevati ELSE NULL END) AS \"Laboratorio\"\r\nFROM Rilevamento\r\nWHERE timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes') AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  AND codice_sensore IN (1, 2, 3)\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento ASC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  MAX(watt_rilevati) AS \"Ufficio 1 max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 1\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes') \r\n                             AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "title": "Potenza Massima per Fase",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "WITH intervallo AS (\r\n  SELECT\r\n    timestamp_rilevamento AS ts\r\n  FROM Rilevamento\r\n  WHERE timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                                AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  GROUP BY timestamp_rilevamento\r\n),\r\nufficio1 AS (\r\n  SELECT\r\n    timestamp_rilevamento AS ts,\r\n    MAX(watt_rilevati) AS ufficio1\r\n  FROM Rilevamento\r\n  WHERE codice_sensore = 1\r\n    AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                                AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  GROUP BY timestamp_rilevamento\r\n),\r\nmagazzino AS (\r\n  SELECT\r\n    timestamp_rilevamento AS ts,\r\n    MAX(watt_rilevati) AS magazzino\r\n  FROM Rilevamento\r\n  WHERE codice_sensore = 2\r\n    AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                                AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  GROUP BY timestamp_rilevamento\r\n),\r\nlaboratorio AS (\r\n  SELECT\r\n    timestamp_rilevamento AS ts,\r\n    MAX(watt_rilevati) AS laboratorio\r\n  FROM Rilevamento\r\n  WHERE codice_sensore = 3\r\n    AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes')\r\n                                AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\n  GROUP BY timestamp_rilevamento\r\n)\r\nSELECT\r\n  i.ts,\r\n  COALESCE(ufficio1.ufficio1, 0) AS \"Ufficio 1\",\r\n  COALESCE(magazzino.magazzino, 0) AS \"Magazzino\",\r\n  COALESCE(laboratorio.laboratorio, 0) AS \"Laboratorio\"\r\nFROM intervallo i\r\nLEFT JOIN ufficio1 ON i.ts = ufficio1.ts\r\nLEFT JOIN magazzino ON i.ts = magazzino.ts\r\nLEFT JOIN laboratorio ON i.ts = laboratorio.ts\r\nORDER BY i.ts ASC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  MAX(watt_rilevati) AS \"Magazzino max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 2\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes') \r\n                             AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp_rilevamento AS ts,\r\n  MAX(watt_rilevati) AS \"Laboratorio max\"\r\nFROM Rilevamento\r\nWHERE codice_sensore = 3\r\n  AND timestamp_rilevamento BETWEEN ($__timeFrom()::timestamp - INTERVAL '15 minutes') \r\n                             AND ($__timeTo()::timestamp + INTERVAL '15 minutes')\r\nGROUP BY timestamp_rilevamento\r\nORDER BY timestamp_rilevamento DESC;\r\n"
    }
   ]
  }
 ]
}